# StartTime.srv

# 요청 부분 (요청 메시지)
string job_list     # 작업 목록 (RED: 0,BLUE: 0)
int32 constatus     # 컨베이어 벨트 동작 상태 값 (1 동작 / 0 정지)
int32 datastatus    # 로봇뷰 이미지 캡쳐 시 전달하는 값 (1 동작)

---

# 응답 부분 (응답 메시지)
string status       # 작업 목록 처리 상태 (SUCCESS / FAILURE)
string conv         # 컨베이어 벨트 동작 처리 상태
string data         # 로봇뷰 이미지 캡쳐 처리 상태 (SUCCESS / FAILURE)
